#!/usr/bin/env python2.7

###
# Requirements:
# * Install sqlite3 and BeautifulSoup modules using PIP
# * Get litepiesql from http://www.kipdola.be/en/blog/skerit/131-introducing-litepiesql-python-sqlite
#   and put it into your python path (most likely next to this script)
###
# Usage: Ask for help using 'vgwort.py -h'
###
# "THE COFFEE-WARE LICENSE" (Revision 42):
# <knut@ahlers.me> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a coffee in return. --Knut
###

import argparse, os

from vgwort import VGWort
from progressbar import progressbar

def main():
  parser = argparse.ArgumentParser(description = 'Local management of VGWort counter marks')
  parser.add_argument('--add-marks', help='Parse csv export of counter marks', metavar='<CSV Document>')
  parser.add_argument('--get-unused', action='store_true', help='Get one unused counter mark')
  parser.add_argument('--refresh-used-marks', help='Scans sitemap.xml for articles using counter marks', metavar='<URL to sitemap.xml>')
  parser.add_argument('--get-url-for-mark', help='Displays found URL for given counter mark', metavar='[mark, [...]]', nargs='*')
  args = parser.parse_args()

  vgw = VGWort(os.path.expanduser('~/.vgwort.db'))
  anyactiontaken = False

  if args.add_marks is not None:
    vgw.add_marks_from_csv(args.add_marks)
    anyactiontaken = True

  if args.get_unused:
    vgw.get_unused_mark()
    anyactiontaken = True

  if args.refresh_used_marks is not None:
    vgw.refresh_used_marks(args.refresh_used_marks)
    anyactiontaken = True

  if args.get_url_for_mark is not None:
    vgw.get_url_for_mark(args.get_url_for_mark)
    anyactiontaken = True

  if not anyactiontaken:
    parser.print_help()


if __name__ == '__main__':
  main()
